### ISSUE TITLE
'Download final data' does not work

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdDwC#13]
![image](https://user-images.githubusercontent.com/16609623/55188799-d74aca00-51a4-11e9-9baf-bc70d77d113d.png)

The file is being downloaded not as CSV file but as RDS.

OS: **Win 10** | MacOS* | Linux*
Browser: **Chrome | Explorer | Edge | Firefox** 
*.Not tested

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=2:2

**Comment by PoGibas** [comment]
Solved with commit https://github.com/bd-R/bdDwC/commit/2fe0ca3f82d10a212a60961ca0970499fc082297

Here I changed `saveRDS` with `data.table::fwrite`. As we're already using `data.table::fread` I'm not increasing number of dependencies. However, `RDS` was used with intention with queried dataset contains list as entries. In this case `csv` file might not work.
