### ISSUE TITLE
No signal/announcement when data is successfully uploaded

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdDwC#14]
For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=3:3

**Comment by PoGibas** [comment]
Solved with commit https://github.com/bd-R/bdDwC/commit/4df325eba4e7cf1cc5bdab059967bdc2b611cd09

Added more informative messages for starting/ending data upload
