### ISSUE TITLE
Empty download query crashes the bdDwC app

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdDwC#15]
**e.g. "concolor" :**
![image](https://user-images.githubusercontent.com/16609623/55225376-83cb9100-5223-11e9-90af-cf449083b715.png)

**Console error message: "Error in if: argument is of length zero" :**
![image](https://user-images.githubusercontent.com/16609623/55225462-b9707a00-5223-11e9-98f5-902b182244d8.png)

### **[[[[[[Also happans in bdchecks]]]]]**

OS: **Win 10** | MacOS* | Linux*
*.Not tested

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=6:6

**Comment by PoGibas** [comment]
Solved with commit https://github.com/bd-R/bdDwC/commit/7c5559783191d5adfee52606d2e8a95661f71f22

Added condition if any data was uploaded (ie., if scientific name has entries). If no data was imported then a pop up message appears and ask to enter different name

**Comment by tom-gu** [comment]
resolved in the new app
