### ISSUE TITLE
Loading data from GBIF crashes app

### ISSUE THREAD

**Issue by thiloshon** [bd-R/bdDwC#16]
Loading data from GBIF errors at 'tolower' function because of non UTF characters. (Non UTF characters cannot be lowercased). Observed in docker environment. Not reproducible in local bdclean.

**Comment by tom-gu** [comment]
![image](https://user-images.githubusercontent.com/16609623/59760549-3e0aeb80-929b-11e9-9a22-2e494ac8cb7e.png)

**Comment by tom-gu** [comment]
resolved
