### ISSUE TITLE
Issue with lowercase in darwinizing

### ISSUE THREAD

**Issue by thiloshon** [bd-R/bdDwC#17]
When darwinizing the following error is produced.

```
Warning: Error in tolower: invalid multibyte string 275
  75: tolower
  74: bdDwC::darwinize_names
  73: a [/Users/thiloshonnagarajah/RProjects/bdclean/inst/shiny/bdclean/server.R#225]
  72: observeEventHandler [/Users/thiloshonnagarajah/RProjects/bdclean/inst/shiny/bdclean/server.R#64]
   1: runApp
```

Used the following dataset,

[vertnet_1r.RDS.zip](https://github.com/bd-R/bdDwC/files/4013930/vertnet_1r.RDS.zip)

**Comment by PoGibas** [comment]
Can you please check with `bdDwC::darwinize_names(as.data.frame(readRDS("vertnet_1r.RDS")), bdDwC:::data_darwin_cloud$data)` I can reproduce this error

**Comment by thiloshon** [comment]
Yes, using bdDwC:::data_darwin_cloud$data solved the issue.
